# Creamos las redes
networks:
  hasher:
    internal: true
  redis:
    internal: true
  rng:
    internal: true
  webui:
    internal: true    
  worker:
    internal: true
  #balanceadores (servicios)
  services:
    hasher:
      deploy:
        mode: replicated
        placement:
          constraint:
            - node.role == worker
        replicas: 1
        resources:
          limits:
            cpus: "0.1"
            memory: 100M
          reservations:
            cpus: "0.1"
            memory: 100M          
    redis:
      internal: true
    rng:
      internal: true
    webui:
      internal: true    
    worker:
      internal: true
  
